create extension if not exists pgcrypto;
create type public.order_status as enum ('pending','paid','processing','shipped','delivered','cancelled','refunded');
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, email text, full_name text, phone text, created_at timestamptz not null default now());
create table public.products (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, description text not null default '', category text not null, price integer not null check(price>=0), image_url text not null, active boolean not null default true, created_at timestamptz not null default now());
create table public.product_variants (id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products on delete cascade, size text not null, sku text unique, stock integer not null default 0 check(stock>=0), unique(product_id,size));
create table public.cart_items (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users on delete cascade, variant_id uuid not null references public.product_variants on delete cascade, quantity integer not null check(quantity between 1 and 20), created_at timestamptz not null default now(), unique(user_id,variant_id));
create table public.wishlists (user_id uuid not null references auth.users on delete cascade, product_id uuid not null references public.products on delete cascade, created_at timestamptz not null default now(), primary key(user_id,product_id));
create table public.addresses (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users on delete cascade, label text not null default 'Home', full_name text not null, phone text not null, line1 text not null, line2 text, city text not null, state text not null, postal_code text, country text not null default 'Nigeria', is_default boolean not null default false, created_at timestamptz not null default now());
create table public.orders (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users on delete restrict, address_id uuid references public.addresses on delete set null, status public.order_status not null default 'pending', subtotal integer not null check(subtotal>=0), shipping integer not null default 0, total integer not null check(total>=0), currency text not null default 'NGN', paystack_reference text unique, paid_at timestamptz, created_at timestamptz not null default now());
create table public.order_items (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders on delete cascade, product_id uuid references public.products on delete set null, variant_id uuid references public.product_variants on delete set null, product_name text not null, size text not null, unit_price integer not null, quantity integer not null check(quantity>0));
create index cart_items_user on public.cart_items(user_id); create index orders_user_created on public.orders(user_id,created_at desc);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,email,full_name) values(new.id,new.email,coalesce(new.raw_user_meta_data->>'full_name',new.raw_user_meta_data->>'name')); return new; end $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
alter table public.profiles enable row level security; alter table public.products enable row level security; alter table public.product_variants enable row level security; alter table public.cart_items enable row level security; alter table public.wishlists enable row level security; alter table public.addresses enable row level security; alter table public.orders enable row level security; alter table public.order_items enable row level security;
create policy "Profiles are readable by owner" on public.profiles for select to authenticated using(id=auth.uid()); create policy "Profiles update own" on public.profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid());
create policy "Active products public" on public.products for select using(active=true); create policy "Variants for active products public" on public.product_variants for select using(exists(select 1 from public.products p where p.id=product_id and p.active));
create policy "Cart owner access" on public.cart_items for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid()); create policy "Wishlist owner access" on public.wishlists for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid()); create policy "Address owner access" on public.addresses for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "Orders owner reads" on public.orders for select to authenticated using(user_id=auth.uid()); create policy "Order items owner reads" on public.order_items for select to authenticated using(exists(select 1 from public.orders o where o.id=order_id and o.user_id=auth.uid()));
insert into storage.buckets(id,name,public) values('product-images','product-images',true) on conflict(id) do nothing;
create policy "Public product images" on storage.objects for select using(bucket_id='product-images');
insert into public.products(id,name,slug,category,price,image_url,description) values
('10000000-0000-4000-8000-000000000001','The Daily Loafer','the-daily-loafer','Loafers',89500,'https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&w=1100&q=85','An easy, considered loafer in supple leather. Built to take you from the first meeting to the last table.'),
('10000000-0000-4000-8000-000000000002','The City Sandal','the-city-sandal','Sandals',64000,'https://images.unsplash.com/photo-1562273138-f46be4ebdf33?auto=format&fit=crop&w=1100&q=85','An uncomplicated sandal with a thoughtful fit and soft, flexible sole. Your warm-weather uniform.'),
('10000000-0000-4000-8000-000000000003','The Weekend Runner','the-weekend-runner','Sneakers',112000,'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1100&q=85','A clean-lined everyday sneaker. Light on the foot, grounded in comfort.'),
('10000000-0000-4000-8000-000000000004','The Soft Step Slide','the-soft-step-slide','Sandals',52000,'https://images.unsplash.com/photo-1603487742131-4160ec999306?auto=format&fit=crop&w=1100&q=85','The slip-on you reach for without thinking. Soft leather, considered proportions.'),
('10000000-0000-4000-8000-000000000005','The After Hours Heel','the-after-hours-heel','Heels',98500,'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=1100&q=85','A sculptural, wearable heel for evenings that stretch into the night.'),
('10000000-0000-4000-8000-000000000006','The Grounded Boot','the-grounded-boot','Boots',138000,'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1100&q=85','A quietly confident leather boot with a grounded profile and all-day ease.') on conflict(slug) do nothing;
insert into public.product_variants(product_id,size,sku,stock) select p.id,s.size,'JICO-'||upper(regexp_replace(p.slug,'-','','g'))||'-'||s.size,10 from public.products p cross join (values('36'),('37'),('38'),('39'),('40'),('41'),('42'),('43'),('44'),('45')) s(size) on conflict(product_id,size) do nothing;
create or replace function public.complete_paid_order(p_reference text,p_user_id uuid,p_paid_at timestamptz) returns void language plpgsql security definer set search_path=public as $$ declare o public.orders%rowtype; i record; begin select * into o from public.orders where paystack_reference=p_reference and user_id=p_user_id for update; if not found then raise exception 'Order not found'; end if; if o.status <> 'pending' then return; end if; for i in select variant_id,quantity from public.order_items where order_id=o.id loop update public.product_variants set stock=stock-i.quantity where id=i.variant_id and stock>=i.quantity; if not found then raise exception 'Insufficient stock'; end if; end loop; update public.orders set status='paid',paid_at=p_paid_at where id=o.id; end $$;
revoke all on function public.complete_paid_order(text,uuid,timestamptz) from public,anon,authenticated; grant execute on function public.complete_paid_order(text,uuid,timestamptz) to service_role;
